// plantData.js
export const plants = {
  chamomile: {
    title: "Chamomile",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Chamomile (Matricaria chamomilla) is a fragrant herb known for its calming properties. It's commonly used in teas and herbal remedies.",
    botanicalName: "Matricaria chamomilla",
    commonNames: ["Chamomile"],
    habitat: "Cultivated in gardens and fields, prefers sunny areas.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Chamomile promotes relaxation, alleviates digestive issues, and improves sleep quality.",
    methodsOfCultivation: "Grown from seeds in well-drained soil and requires full sun.",
    leaf: {
      description: "Chamomile leaves are feathery and aromatic, used in teas and remedies.",
      benefits: "Help in digestion and can be used in herbal infusions.",
    },
    stem: {
      description: "The stem is erect and has a few branches, often used for making extracts.",
      benefits: "Can be used to prepare soothing teas and oils.",
    },
    flower: {
      description: "The flower heads are daisy-like and are the main part used in herbal medicine.",
      benefits: "Known for their calming effects and ability to help with sleep disorders.",
    },
  },
  giloy: {
    title: "Giloy",
    modelUrl: "/assets/models/giloy.glb",
    description: "Giloy, also known as Tinospora cordifolia, is a climbing shrub traditionally used in Ayurveda for its wide range of medicinal benefits. Known for its bitter taste, the plant is prized for its ability to boost immunity, fight infections, and detoxify the body.",
    botanicalName: "Tinospora cordifolia",
    commonNames: ["Giloy", "Heart-leaved Moonseed"],
    habitat: "Tropical forests, often found climbing on trees.",
    theme: "Immunity Booster",
    mostlyUsedIn: ["Ayurveda", "Homeopathy"],
    medicinalUses: "Giloy is renowned for its anti-inflammatory, antioxidant, and anti-diabetic properties. It is commonly used to treat fever, improve digestion, and enhance liver function.",
    methodsOfCultivation: "Giloy can be propagated from stem cuttings or seeds. It thrives in well-drained soil and requires moderate sunlight. Regular watering is essential, especially during dry spells.",
  },
  turmeric: {
    title: "Turmeric",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Turmeric (Curcuma longa) is a vibrant yellow rhizome known for its culinary and medicinal uses. It contains curcumin, a potent compound that contributes to its anti-inflammatory and antioxidant properties.",
    botanicalName: "Curcuma longa",
    commonNames: ["Turmeric", "Curcumin"],
    habitat: "Tropical and subtropical regions, particularly in India and Southeast Asia.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda", "Homeopathy"],
    medicinalUses: "Turmeric is widely used to alleviate joint pain, improve skin health, and enhance overall wellness. It's also known for its role in supporting digestive health and reducing inflammation.",
    methodsOfCultivation: "Turmeric is grown from rhizomes planted in well-drained, fertile soil with good moisture retention. It requires partial to full sunlight and should be watered regularly to keep the soil consistently moist.",
  },
  amla: {
    title: "Amla",
    modelUrl: "/assets/models/amla.glb",
    description: "Amla, or Phyllanthus emblica, is a small green fruit renowned for its high vitamin C content and potent antioxidant properties. This plant is a staple in Ayurvedic medicine, valued for its ability to promote overall health.",
    botanicalName: "Phyllanthus emblica",
    commonNames: ["Indian Gooseberry", "Amla"],
    habitat: "Deciduous forests and along riverbanks across India and Southeast Asia.",
    theme: "Immunity Booster",
    mostlyUsedIn: ["Ayurveda", "Naturopathy"],
    medicinalUses: "Amla supports the immune system, enhances skin health, and aids digestion. It is often used to prevent hair loss and promote healthy hair growth.",
    methodsOfCultivation: "Amla can be grown from seeds or grafts in well-drained soil. It prefers full sunlight and needs regular watering, especially in the initial growth stages.",
  },
  moringa: {
    title: "Moringa",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Moringa, commonly referred to as the 'miracle tree,' is recognized for its extraordinary nutritional profile. Moringa leaves are rich in vitamins, minerals, and amino acids, making them an excellent dietary supplement.",
    botanicalName: "Moringa oleifera",
    commonNames: ["Drumstick Tree", "Miracle Tree"],
    habitat: "Tropical and subtropical regions, often found in poor soils.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda", "Naturopathy"],
    medicinalUses: "Moringa is used to combat malnutrition, support energy levels, and improve digestive health. Its anti-inflammatory properties also make it beneficial for reducing swelling and pain.",
    methodsOfCultivation: "Moringa is grown from seeds or cuttings, thriving in well-drained, sandy soil. It requires full sunlight and moderate watering, being drought-resistant once established.",
  },
  jalapeno: {
    title: "Jalapeno",
    modelUrl: "/assets/models/jalapeno.glb",
    description: "Jalapeno (Capsicum annuum) is a medium-sized chili pepper known for its spicy flavor and health benefits. It's widely used in various cuisines, particularly in Mexican dishes.",
    botanicalName: "Capsicum annuum",
    commonNames: ["Jalapeno Pepper"],
    habitat: "Native to Mexico, cultivated in warm climates worldwide.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda", "Naturopathy"],
    medicinalUses: "Jalapenos may help boost metabolism, support cardiovascular health, and provide anti-inflammatory benefits. Their high vitamin C content is also beneficial for the immune system.",
    methodsOfCultivation: "Jalapenos are grown from seeds and require warm temperatures, full sun, and well-drained soil. Regular watering is important, especially during flowering and fruiting.",
  },
  maple: {
    title: "Maple",
    modelUrl: "/assets/models/maple.glb",
    description: "Maple trees (Acer spp.) are celebrated for their stunning foliage and the production of maple syrup. They are also valued for their wood and ecological benefits.",
    botanicalName: "Acer spp.",
    commonNames: ["Maple Tree"],
    habitat: "Temperate forests, particularly in North America and Europe.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Maple syrup is rich in antioxidants and may have anti-inflammatory properties. The leaves and bark are sometimes used in traditional remedies.",
    methodsOfCultivation: "Maple trees are grown from seeds or cuttings and thrive in well-drained, fertile soil. They require full sunlight and adequate moisture, especially in dry seasons.",
  },
  cannabis: {
    title: "Cannabis",
    modelUrl: "/assets/models/cannabis.glb",
    description: "Cannabis (Cannabis sativa) is a versatile plant used for its psychoactive properties and various medicinal benefits. It has gained popularity in recent years for its therapeutic applications.",
    botanicalName: "Cannabis sativa",
    commonNames: ["Bhaang", "Marijuana"],
    habitat: "Widely cultivated in various climates around the world.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda", "Unani"],
    medicinalUses: "Cannabis is used for pain relief, reducing anxiety, and treating chronic conditions. Its compounds, such as CBD and THC, have shown promise in medical research.",
    methodsOfCultivation: "Cannabis is grown from seeds and requires a warm climate, adequate sunlight, and well-drained soil. Careful attention to nutrient levels and watering is crucial for optimal growth.",
  },
  lupine: {
    title: "Lupine",
    modelUrl: "/assets/models/lupine.glb",
    description: "Lupine (Lupinus spp.) is a flowering plant characterized by its beautiful, tall spikes of flowers. It is often used in gardens for ornamental purposes and has some nutritional value.",
    botanicalName: "Lupinus spp.",
    commonNames: ["Lupin"],
    habitat: "Various environments, commonly found in dry, sandy soils.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Lupine seeds are high in protein and fiber and can be used in various culinary applications. They are also known for their potential health benefits, including cholesterol reduction.",
    methodsOfCultivation: "Lupines are grown from seeds and prefer well-drained soil in full sun. They are drought-tolerant and require minimal maintenance once established.",
  },
  wildGarlic: {
    title: "Wild Garlic",
    modelUrl: "/assets/models/wild_garlic.glb",
    description: "Wild garlic (Allium ursinum) is a perennial plant known for its distinctive garlicky aroma and flavor. It is commonly found in woodland areas and is valued for its culinary and medicinal uses.",
    botanicalName: "Allium ursinum",
    commonNames: ["Ramsons", "Wild Leek"],
    habitat: "Wooded areas and shady environments, especially in damp soils.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Wild garlic is used for its antibacterial and antifungal properties. It's also believed to support heart health and improve circulation.",
    methodsOfCultivation: "Wild garlic can be propagated from bulbs or seeds. It prefers moist, shaded areas and should be watered regularly, especially in dry periods.",
  },
  bulrush: {
    title: "Bulrush",
    modelUrl: "/assets/models/bulrush.glb",
    description: "Bulrush (Schoenoplectus spp.) is a wetland plant characterized by its tall, grass-like appearance. It plays an important ecological role in wetland habitats.",
    botanicalName: "Schoenoplectus spp.",
    commonNames: ["Bulrush", "Sedge"],
    habitat: "Wetlands, marshes, and along the edges of lakes and rivers.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda"],
    medicinalUses: "Bulrush has traditionally been used to treat various ailments, including urinary issues and skin conditions, due to its anti-inflammatory properties.",
    methodsOfCultivation: "Bulrush is grown in wet, marshy conditions, usually from rhizomes or seeds. It thrives in full sun and requires consistent moisture.",
  },
  borage: {
    title: "Borage",
    modelUrl: "/assets/models/borage.glb",
    description: "Borage (Borago officinalis) is an herb known for its star-shaped blue flowers and cucumber-like flavor. It's often used in culinary dishes and herbal remedies.",
    botanicalName: "Borago officinalis",
    commonNames: ["Borage", "Starflower"],
    habitat: "Gardens and disturbed areas, commonly found in Europe and Asia.",
    theme: "Skincare",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Borage oil is rich in gamma-linolenic acid (GLA), known for its anti-inflammatory properties. It's often used to improve skin health and treat conditions like eczema.",
    methodsOfCultivation: "Borage is grown from seeds and prefers well-drained soil in full sun. It's drought-tolerant and requires minimal care once established.",
  },
  argentinaAnserina: {
    title: "Argentina Anserina",
    modelUrl: "/assets/models/argentina_anserina.glb",
    description: "Argentina anserina, commonly known as Silverweed, is a perennial herb found in various habitats. It has a long history of use in traditional medicine.",
    botanicalName: "Argentina anserina",
    commonNames: ["Silverweed"],
    habitat: "Wet meadows and coastal areas.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Used to treat digestive issues and promote wound healing due to its astringent properties.",
    methodsOfCultivation: "Grown from seeds or divisions, Silverweed prefers moist, well-drained soil and partial shade.",
  },
  genista: {
    title: "Genista",
    modelUrl: "/assets/models/genista.glb",
    description: "Genista is a genus of flowering plants commonly known as gorse or broom. These plants are recognized for their bright yellow flowers and potential medicinal properties.",
    botanicalName: "Genista spp.",
    commonNames: ["Broom"],
    habitat: "Dry, sandy soils and open woodland areas.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Traditionally used for its diuretic properties and to support urinary tract health.",
    methodsOfCultivation: "Genista can be propagated from seeds or cuttings, preferring well-drained soil and full sun exposure.",
  },
  gagea: {
    title: "Gagea",
    modelUrl: "/assets/models/gagea.glb",
    description: "Gagea is a genus of flowering plants in the lily family, known for their delicate yellow flowers. They are often found in grasslands and forest edges.",
    botanicalName: "Gagea spp.",
    commonNames: ["Gagea"],
    habitat: "Grasslands and wooded areas across Europe and Asia.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Used traditionally to alleviate respiratory ailments and promote overall wellness.",
    methodsOfCultivation: "Gagea can be grown from bulbs or seeds, preferring well-drained soil and partial shade.",
  },
  nettle: {
    title: "Nettle",
    modelUrl: "/assets/models/nettle.glb",
    description: "Nettle (Urtica dioica) is a perennial herb known for its stinging hairs and nutritional value. It's commonly used in herbal medicine and cuisine.",
    botanicalName: "Urtica dioica",
    commonNames: ["Stinging Nettle"],
    habitat: "Wooded areas, hedgerows, and disturbed soils.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda", "Naturopathy"],
    medicinalUses: "Nettle is rich in vitamins and minerals. It's often used to support joint health, alleviate allergies, and improve skin conditions.",
    methodsOfCultivation: "Nettle can be grown from seeds or divisions, preferring rich, moist soil and partial shade. Regular watering is essential for optimal growth.",
  },
  blackberry: {
    title: "Blackberry",
    modelUrl: "/assets/models/blackberry.glb",
    description: "Blackberry (Rubus fruticosus) is a thorny shrub known for its sweet, juicy berries. It's popular in culinary applications and has various health benefits.",
    botanicalName: "Rubus fruticosus",
    commonNames: ["Blackberry"],
    habitat: "Woodlands, hedgerows, and gardens.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Rich in vitamins, antioxidants, and dietary fiber, blackberries support heart health and digestion.",
    methodsOfCultivation: "Blackberries are grown from seeds or cuttings and prefer well-drained soil with full sun. They require regular pruning to promote healthy growth and fruit production.",
  },
  daisies: {
    title: "Daisies",
    modelUrl: "/assets/models/daisies.glb",
    description: "Daisies (Bellis perennis) are flowering plants known for their vibrant blooms and medicinal properties. They are often found in meadows and gardens.",
    botanicalName: "Bellis perennis",
    commonNames: ["Common Daisy"],
    habitat: "Meadows and grassy areas.",
    theme: "Medicinal",
    mostlyUsedIn: ["Homeopathy"],
    medicinalUses: "Daisies are used for their anti-inflammatory properties and can be applied topically to soothe skin irritations.",
    methodsOfCultivation: "Daisies are grown from seeds and prefer well-drained soil and full sun. They require moderate watering, especially during dry periods.",
  },
  dock: {
    title: "Dock",
    modelUrl: "/assets/models/dock.glb",
    description: "Dock (Rumex spp.) is a perennial plant characterized by its large leaves and potential health benefits. It is commonly found in damp areas.",
    botanicalName: "Rumex spp.",
    commonNames: ["Dock Leaf"],
    habitat: "Wet meadows and disturbed areas.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda"],
    medicinalUses: "Dock is known for its astringent properties and is traditionally used to treat digestive issues and skin irritations.",
    methodsOfCultivation: "Dock can be grown from seeds or divisions, preferring moist, rich soil and partial shade.",
  },
  brookmint: {
    title: "Brookmint",
    modelUrl: "/assets/models/brookmint.glb",
    description: "Brookmint (Mentha aquatica) is a herbaceous plant known for its aromatic leaves. It grows near water bodies and has culinary and medicinal uses.",
    botanicalName: "Mentha aquatica",
    commonNames: ["Water Mint"],
    habitat: "Wetlands and along streams.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Brookmint is used for digestive issues and has soothing properties for stomach ailments.",
    methodsOfCultivation: "Brookmint is grown from cuttings or seeds and prefers moist conditions with partial shade.",
  },
  valerian: {
    title: "Valerian",
    modelUrl: "/assets/models/valerian.glb",
    description: "Valerian (Valeriana officinalis) is a flowering plant known for its calming effects. It's often used as a natural remedy for anxiety and sleep disorders.",
    botanicalName: "Valeriana officinalis",
    commonNames: ["Valerian Root"],
    habitat: "Moist meadows and woodlands.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Valerian is used to promote relaxation, alleviate insomnia, and reduce anxiety. It's often consumed as a tea or in supplement form.",
    methodsOfCultivation: "Valerian can be grown from seeds or root divisions in rich, moist soil. It prefers partial shade and requires regular watering.",
  },
  groundsel: {
    title: "Groundsel",
    modelUrl: "/assets/models/groundsel.glb",
    description: "Groundsel (Senecio vulgaris) is a flowering plant known for its fast growth and adaptability. It is often found in disturbed areas.",
    botanicalName: "Senecio vulgaris",
    commonNames: ["Groundsel"],
    habitat: "Disturbed areas and waste ground.",
    theme: "Medicinal",
    mostlyUsedIn: ["Homeopathy"],
    medicinalUses: "Traditionally used for various ailments, including digestive issues and respiratory conditions.",
    methodsOfCultivation: "Groundsel is grown from seeds and thrives in well-drained soil. It is drought-tolerant and requires minimal care once established.",
  },
  raspberry: {
    title: "Raspberry",
    modelUrl: "/assets/models/raspberry.glb",
    description: "Raspberry (Rubus idaeus) is a thorny shrub valued for its sweet, red fruit. It is widely cultivated for culinary purposes and has several health benefits.",
    botanicalName: "Rubus idaeus",
    commonNames: ["Raspberry"],
    habitat: "Woodlands and gardens.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Raspberries are rich in antioxidants and vitamins, supporting immune function and heart health.",
    methodsOfCultivation: "Raspberries are grown from seeds or cuttings and prefer well-drained soil with full sun. They require regular pruning and watering.",
  },
  coltsfoot: {
    title: "Coltsfoot",
    modelUrl: "/assets/models/coltsfoot.glb",
    description: "Coltsfoot (Tussilago farfara) is a perennial herb known for its yellow flowers and broad leaves. It has a long history of use in herbal medicine.",
    botanicalName: "Tussilago farfara",
    commonNames: ["Coltsfoot"],
    habitat: "Wet meadows and along roadsides.",
    theme: "Medicinal",
    mostlyUsedIn: ["Homeopathy"],
    medicinalUses: "Coltsfoot is traditionally used to relieve coughs and respiratory issues due to its soothing properties.",
    methodsOfCultivation: "Coltsfoot can be grown from seeds and prefers moist, rich soil. It thrives in partial to full sunlight and requires regular watering.",
  },
  maizecorn: {
    title: "Maizecorn",
    modelUrl: "/assets/models/maizecorn.glb",
    description: "Maizecorn (Zea mays) is a staple cereal crop known for its versatility in food products. It's also used for its nutritional benefits.",
    botanicalName: "Zea mays",
    commonNames: ["Corn", "Maize"],
    habitat: "Cultivated in a variety of environments, particularly in warm climates.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Corn is rich in vitamins and fiber, promoting digestive health and providing energy.",
    methodsOfCultivation: "Maizecorn is grown from seeds in well-drained soil with full sun. Regular watering and pest management are essential for successful cultivation.",
  },
  aloevera: {
    title: "Aloe Vera",
    modelUrl: "/assets/models/aloevera.glb",
    description: "Aloe Vera (Aloe barbadensis) is a succulent plant known for its soothing gel and numerous health benefits. It has been used for centuries in traditional medicine.",
    botanicalName: "Aloe barbadensis",
    commonNames: ["Aloe Vera"],
    habitat: "Tropical and subtropical regions.",
    theme: "Skincare",
    mostlyUsedIn: ["Ayurveda", "Naturopathy"],
    medicinalUses: "Aloe Vera is known for its skin-soothing properties, treating burns, and promoting wound healing. It is also consumed for digestive health.",
    methodsOfCultivation: "Aloe Vera is grown from offsets or seeds in well-drained soil with full sun. It requires minimal watering and is drought-resistant.",
  },
  jadePlant: {
    title: "Jade Plant",
    modelUrl: "/assets/models/jade_plant.glb",
    description: "The Jade Plant (Crassula ovata) is a succulent known for its attractive, fleshy leaves and ease of care. It is often associated with good luck and prosperity.",
    botanicalName: "Crassula ovata",
    commonNames: ["Jade Plant", "Money Tree"],
    habitat: "Native to South Africa, often grown indoors in pots.",
    theme: "Skincare",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "While primarily grown as an ornamental plant, its leaves have been used in traditional remedies for skin irritations.",
    methodsOfCultivation: "Jade plants are grown from leaves or stem cuttings, thriving in well-drained soil with bright sunlight. They require minimal watering.",
  },
  maleFern: {
    title: "Male Fern",
    modelUrl: "/assets/models/male_fern.glb",
    description: "Male Fern (Dryopteris filix-mas) is a hardy fern known for its feathery fronds. It has a long history of medicinal use, particularly in herbal remedies.",
    botanicalName: "Dryopteris filix-mas",
    commonNames: ["Male Fern"],
    habitat: "Wooded areas and shaded locations.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Traditionally used for its potential to expel intestinal worms and treat various skin conditions.",
    methodsOfCultivation: "Male Fern can be propagated by spores or divisions, preferring rich, moist soil in partial to full shade.",
  },
  
  neem: {
    title: "Neem",
    modelUrl: "/assets/models/neem.glb",
    description: "Neem (Azadirachta indica) is a fast-growing tree known for its medicinal properties. Every part of the tree is utilized in traditional medicine.",
    botanicalName: "Azadirachta indica",
    commonNames: ["Neem", "Indian Lilac"],
    habitat: "Tropical and subtropical regions, commonly found in India.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda", "Unani"],
    medicinalUses: "Neem is used for its antibacterial, antifungal, and antiviral properties. It's commonly applied in skin treatments and dental care.",
    methodsOfCultivation: "Neem can be grown from seeds or cuttings in well-drained soil. It prefers full sun and is drought-resistant once established.",
  },
};
