export const plants = {
  chamomile: {
    title: "Chamomile",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Chamomile (Matricaria chamomilla) is a fragrant herb used in traditional medicine for its calming properties. It is commonly used in teas to relieve anxiety, promote sleep, and soothe the digestive system. Chamomile grows in gardens and fields and is characterized by its daisy-like flowers.",
    botanicalName: "Matricaria chamomilla",
    commonNames: ["Chamomile"],
    habitat: "Cultivated in sunny gardens and open fields, prefers well-drained soil.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Chamomile is well-known for promoting relaxation, easing digestive discomfort, and aiding sleep. It also has anti-inflammatory and antioxidant properties.",
    methodsOfCultivation: "Chamomile can be grown from seeds in well-drained soil and requires full sun for optimal growth. Regular watering is essential.",
    leaf: {
      description: "Chamomile leaves are finely divided and feathery, giving the plant a delicate, soft appearance.",
      benefits: "Used to aid digestion and as an ingredient in calming herbal infusions.",
    },
    stem: {
      description: "The stem is slender, erect, and sometimes branched, growing up to 24 inches in height.",
      benefits: "The stem can be used to make extracts for soothing teas and oils.",
    },
    flower: {
      description: "The flowers are daisy-like with white petals and a yellow center, known for their use in herbal medicine.",
      benefits: "Chamomile flowers are valued for their calming effects and ability to improve sleep and reduce anxiety.",
    },
    link: "https://youtu.be/ibXazvct4KI",
  },
  giloy: {
    title: "Giloy",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Giloy (Tinospora cordifolia) is a climbing shrub known for its extensive medicinal properties. It has been used in Ayurveda to boost immunity, treat fever, and detoxify the body. Giloy is recognized for its bitter taste and heart-shaped leaves.",
    botanicalName: "Tinospora cordifolia",
    commonNames: ["Giloy", "Heart-leaved Moonseed"],
    habitat: "Found in tropical forests, often climbing on trees.",
    theme: "Immunity Booster",
    mostlyUsedIn: ["Ayurveda", "Homeopathy"],
    medicinalUses: "Giloy is used for its anti-inflammatory, antioxidant, and antipyretic properties. It is commonly prescribed to treat fever, boost the immune system, and improve liver function.",
    methodsOfCultivation: "Giloy is grown from stem cuttings in well-drained soil and requires moderate sunlight and regular watering.",
    leaf: {
      description: "The leaves are heart-shaped and bright green, rich in medicinal compounds.",
      benefits: "Used to boost immunity and improve health.",
    },
    stem: {
      description: "The woody stem is the primary part used in medicine and is rich in bioactive compounds.",
      benefits: "Used to make juices and powders for treating fever and improving digestion.",
    },
    flower: {
      description: "Small, yellow-green flowers appear in clusters, contributing to the plant’s overall medicinal properties.",
      benefits: "Flowers play a minor role but are essential to the plant's vitality.",
    },
    link: "https://youtu.be/SvXgRQ-LASI",
  },
  turmeric: {
    title: "Turmeric",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Turmeric (Curcuma longa) is a bright yellow rhizome known for its culinary and medicinal uses. It contains curcumin, which has strong anti-inflammatory and antioxidant properties. It is widely used in Ayurveda to treat various conditions.",
    botanicalName: "Curcuma longa",
    commonNames: ["Turmeric", "Curcumin"],
    habitat: "Native to tropical and subtropical regions, particularly in India and Southeast Asia.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda", "Homeopathy", "Siddha"],
    medicinalUses: "Turmeric is used to reduce inflammation, improve skin health, and support digestive health. It is also effective in alleviating joint pain and improving overall wellness.",
    methodsOfCultivation: "Turmeric is grown from rhizomes planted in well-drained, fertile soil. It requires partial to full sunlight and regular watering to keep the soil moist.",
    leaf: {
      description: "The leaves are large and oblong, growing from long petioles.",
      benefits: "They are occasionally used in cooking and herbal preparations.",
    },
    stem: {
      description: "The stem is a rhizome, growing underground and producing shoots.",
      benefits: "The rhizome is used to produce turmeric powder, widely known for its medicinal and culinary properties.",
    },
    flower: {
      description: "Turmeric flowers are pale yellow and grow in spikes, although they are rarely harvested.",
      benefits: "Turmeric flowers are more ornamental, adding beauty to the plant.",
    },
    link: "https://youtu.be/Zqp6NTJKSLA",
  },
  amla: {
    title: "Amla",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Amla (Phyllanthus emblica), also known as Indian Gooseberry, is prized for its high vitamin C content and antioxidant properties. This small green fruit is a staple in Ayurvedic medicine and is used to promote overall health.",
    botanicalName: "Phyllanthus emblica",
    commonNames: ["Indian Gooseberry", "Amla"],
    habitat: "Grows in deciduous forests and along riverbanks across India and Southeast Asia.",
    theme: "Immunity Booster",
    mostlyUsedIn: ["Ayurveda", "Naturopathy", "Siddha"],
    medicinalUses: "Amla supports the immune system, promotes skin health, and aids digestion. It is also used to prevent hair loss and promote hair growth.",
    methodsOfCultivation: "Amla is grown from seeds or grafts in well-drained soil. It thrives in full sunlight and needs regular watering during early growth stages.",
    leaf: {
      description: "Small, linear leaves arranged in feather-like sprays.",
      benefits: "Used in traditional medicine for their astringent properties.",
    },
    stem: {
      description: "The trunk is crooked with light gray bark.",
      benefits: "The bark is used in some traditional medicines.",
    },
    flower: {
      description: "Small, inconspicuous greenish-yellow flowers that develop into the fruit.",
      benefits: "The flowers play a minor role, but the resulting fruit is rich in nutrients and vitamins.",
    },
    link: "https://youtu.be/MpYt0Dw61Ak",
  },
  moringa: {
    title: "Moringa",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Moringa (Moringa oleifera), also known as the Miracle Tree, is highly valued for its nutritional and medicinal benefits. The leaves are rich in vitamins, minerals, and amino acids, making it an excellent dietary supplement.",
    botanicalName: "Moringa oleifera",
    commonNames: ["Drumstick Tree", "Miracle Tree"],
    habitat: "Native to tropical and subtropical regions, often found in poor soils.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda", "Naturopathy"],
    medicinalUses: "Moringa is used to combat malnutrition, support energy levels, and improve digestive health. Its anti-inflammatory properties are also useful in reducing swelling and pain.",
    methodsOfCultivation: "Moringa is grown from seeds or cuttings, thriving in well-drained, sandy soil. It requires full sunlight and moderate watering.",
    leaf: {
      description: "The leaves are compound, consisting of small, oval-shaped leaflets. They are highly nutritious.",
      benefits: "Used in cooking, teas, and dietary supplements.",
    },
    stem: {
      description: "The stem is fast-growing with soft wood and can be pruned regularly.",
      benefits: "Young stems are edible and add mild flavor to dishes.",
    },
    flower: {
      description: "Fragrant, cream-colored flowers appear in drooping panicles.",
      benefits: "Moringa flowers are edible and can be used in salads or teas.",
    },
    link: "https://youtu.be/864ZbDaOKfc",
  },
  jalapeno: {
    title: "Jalapeno",
    modelUrl: "/assets/models/jalapeno.glb",
    description: "Jalapeno (Capsicum annuum) is a medium-sized chili pepper known for its spicy flavor and nutritional benefits. It is widely used in Mexican cuisine and has numerous health benefits, including supporting cardiovascular health.",
    botanicalName: "Capsicum annuum",
    commonNames: ["Jalapeno Pepper"],
    habitat: "Native to Mexico, jalapenos are cultivated in warm climates worldwide.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda", "Naturopathy"],
    medicinalUses: "Jalapenos may boost metabolism, support cardiovascular health, and provide anti-inflammatory benefits. They are rich in vitamin C, which supports immune function.",
    methodsOfCultivation: "Jalapenos are grown from seeds and require warm temperatures, full sun, and well-drained soil. Regular watering is essential, particularly during flowering and fruiting.",
    leaf: {
      description: "The leaves are smooth, green, and oval-shaped.",
      benefits: "Although not commonly used, they contain some beneficial compounds.",
    },
    stem: {
      description: "The stem is sturdy and green, supporting the plant and peppers.",
      benefits: "It plays a structural role, essential for pepper production.",
    },
    flower: {
      description: "Small, white flowers that develop into the jalapeno peppers.",
      benefits: "Essential for pepper production.",
    },
    link: "https://youtu.be/iX9qOwuD8uo",
  },
  maple: {
    title: "Maple",
    modelUrl: "/assets/models/maple.glb",
    description: "Maple trees (Acer spp.) are known for their vibrant foliage and the production of maple syrup. They are also valued for their wood and ecological benefits.",
    botanicalName: "Acer spp.",
    commonNames: ["Maple Tree"],
    habitat: "Temperate forests, especially in North America and Europe.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Maple syrup is rich in antioxidants and may have anti-inflammatory properties. The leaves and bark are sometimes used in traditional remedies.",
    methodsOfCultivation: "Maple trees are grown from seeds or cuttings and thrive in fertile, well-drained soil with full sunlight.",
    leaf: {
      description: "Maple leaves are lobed and often display vibrant colors in autumn.",
      benefits: "Some traditional remedies use maple leaves for their astringent properties.",
    },
    stem: {
      description: "The tree's strong, woody trunk and branches are prized for timber and syrup production.",
      benefits: "Maple sap is used to produce maple syrup, which contains minerals and antioxidants.",
    },
    flower: {
      description: "Small, inconspicuous flowers that appear before or with the leaves in spring.",
      benefits: "The flowers are vital for seed production.",
    },
    link: "https://youtu.be/gqUhkr1pewM",
  },
  // Continue similarly for all remaining plants...

  cannabis: {
    title: "Cannabis",
    modelUrl: "/assets/models/cannabis.glb",
    description: "Cannabis (Cannabis sativa) is a highly versatile plant used for its psychoactive properties, industrial applications, and medicinal benefits. It contains cannabinoids such as THC and CBD, which have shown promise in treating various medical conditions.",
    botanicalName: "Cannabis sativa",
    commonNames: ["Bhaang", "Marijuana"],
    habitat: "Widely cultivated in various climates across the world.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda", "Unani"],
    medicinalUses: "Cannabis is used to relieve pain, reduce anxiety, and treat chronic conditions. It is also used in treating nausea, muscle spasms, and some neurological conditions.",
    methodsOfCultivation: "Cannabis is grown from seeds and requires a warm climate, well-drained soil, and full sunlight. Careful attention to watering and nutrients is essential for optimal growth.",
    leaf: {
      description: "The leaves are distinctive and palmate with serrated edges. They are a key source of the plant's medicinal cannabinoids.",
      benefits: "Cannabinoid-rich leaves are used in medicinal extracts and oils for various health conditions.",
    },
    stem: {
      description: "The stem is fibrous and strong, especially in hemp varieties, which are used in industrial applications.",
      benefits: "In addition to medicinal use, the stems are used for producing fiber (hemp) for textiles and rope.",
    },
    flower: {
      description: "The flowers are small and grow in clusters, often covered in resinous trichomes, rich in THC and CBD.",
      benefits: "Flowers are the main source of cannabinoids used for both recreational and medicinal purposes.",
    },
    link: "https://youtu.be/Wh96c-lrQEA",
  },
  lupine: {
    title: "Lupine",
    modelUrl: "/assets/models/lupine.glb",
    description: "Lupine (Lupinus spp.) is a flowering plant recognized for its tall, vibrant flower spikes. It is grown ornamentally but also has nutritional value, especially the seeds which are high in protein.",
    botanicalName: "Lupinus spp.",
    commonNames: ["Lupin"],
    habitat: "Grows in dry, sandy soils, commonly in temperate regions.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Lupine seeds are rich in fiber and protein, making them useful for heart health and digestion. Some species have been used to reduce cholesterol levels.",
    methodsOfCultivation: "Lupine is grown from seeds and prefers well-drained soil in full sun. It is drought-tolerant and requires minimal maintenance once established.",
    leaf: {
      description: "The leaves are palmate, with multiple leaflets arranged in a circular pattern.",
      benefits: "While not used medicinally, lupine leaves contribute to the plant’s beauty and are essential for photosynthesis.",
    },
    stem: {
      description: "Erect stems can grow up to several feet, supporting the flower spikes.",
      benefits: "Stems provide structural support for the flowers but are not used medicinally.",
    },
    flower: {
      description: "Lupine flowers are colorful and pea-like, growing in tall spikes. They can be blue, purple, pink, or yellow.",
      benefits: "Ornamental, though the seeds have significant nutritional value in some species.",
    },
    link: "https://youtu.be/dpc8mP-bbHs",
  },
  wildgarlic: {
    title: "Wild Garlic",
    modelUrl: "/assets/models/wildgarlic.glb",
    description: "Wild Garlic (Allium ursinum) is a perennial herb commonly found in woodlands, known for its strong garlicky aroma and flavor. It is valued both for its culinary uses and its medicinal properties.",
    botanicalName: "Allium ursinum",
    commonNames: ["Ramsons", "Wild Leek"],
    habitat: "Thrives in shaded, damp environments such as woodlands.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Wild Garlic has antibacterial and antifungal properties. It is believed to support heart health, lower blood pressure, and improve circulation.",
    methodsOfCultivation: "It is grown from bulbs or seeds, preferring moist soil and shaded areas. Regular watering is required during dry periods.",
    leaf: {
      description: "Broad, elliptical leaves that release a strong garlic scent when crushed.",
      benefits: "Used in culinary dishes and herbal remedies. The leaves are rich in vitamins and minerals.",
    },
    stem: {
      description: "The stem is short and supports the leaves and flower stalks.",
      benefits: "Although not typically used, the stem connects the edible leaves to the bulb.",
    },
    flower: {
      description: "The flowers are small, star-shaped, and white, often used as a garnish or in salads.",
      benefits: "Wild Garlic flowers are edible and decorative, adding a mild garlic flavor to dishes.",
    },
    link: "https://youtu.be/1_HcXGRtM-s",
  },
  bulrush: {
    title: "Bulrush",
    modelUrl: "/assets/models/bulrush.glb",
    description: "Bulrush (Schoenoplectus spp.) is a tall, grass-like wetland plant. It plays a vital role in wetland ecosystems and has been used traditionally in basket-making and for medicinal purposes.",
    botanicalName: "Schoenoplectus spp.",
    commonNames: ["Bulrush", "Sedge"],
    habitat: "Commonly found in wetlands, marshes, and along the edges of lakes and rivers.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda"],
    medicinalUses: "Bulrush has been traditionally used to treat urinary issues and skin conditions due to its anti-inflammatory properties.",
    methodsOfCultivation: "Bulrush is grown in wet, marshy conditions, typically from rhizomes or seeds. It thrives in full sun and requires consistent moisture.",
    leaf: {
      description: "The leaves are long, narrow, and often reduced to sheaths at the base of the stem.",
      benefits: "Though not commonly used medicinally, they play a vital role in the plant’s survival.",
    },
    stem: {
      description: "The stem is tall, green, and cylindrical, growing several feet in height.",
      benefits: "Stems have been used traditionally for weaving baskets and mats.",
    },
    flower: {
      description: "The flowers are small, brown spikelets clustered at the top of the stem.",
      benefits: "While not used medicinally, they are essential for reproduction and provide food for wildlife.",
    },
    link: "https://youtu.be/BbYbugvwuvI",
  },
  borage: {
    title: "Borage",
    modelUrl: "/assets/models/borage.glb",
    description: "Borage (Borago officinalis) is a hardy herb known for its star-shaped blue flowers and cucumber-like flavor. It is often grown in gardens for both its culinary and medicinal uses.",
    botanicalName: "Borago officinalis",
    commonNames: ["Borage", "Starflower"],
    habitat: "Borage grows in gardens and disturbed areas, commonly found in Europe and Asia.",
    theme: "Skincare",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Borage oil is rich in gamma-linolenic acid (GLA), which has anti-inflammatory properties. It is commonly used to improve skin health and treat conditions like eczema.",
    methodsOfCultivation: "Borage is grown from seeds and prefers well-drained soil in full sun. It is drought-tolerant and requires minimal care.",
    leaf: {
      description: "The leaves are oval, hairy, and have a cucumber-like flavor.",
      benefits: "Used in salads, soups, and herbal teas. Rich in vitamins and minerals.",
    },
    stem: {
      description: "Hollow and hairy, the stem can grow up to 2-3 feet tall.",
      benefits: "While not typically used medicinally, the stem supports the plant’s growth and flower production.",
    },
    flower: {
      description: "Borage flowers are star-shaped and usually blue, though they can also be pink or white.",
      benefits: "The flowers are edible and are often used in salads and garnishes. Borage oil extracted from the seeds is widely used in skincare products.",
    },
    link: "https://youtu.be/D16Iw-1dh38",
  },
  argentinaanserina: {
    title: "Argentina Anserina",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Argentina Anserina, commonly known as Silverweed, is a perennial herb that thrives in moist environments. It has a long history of use in traditional medicine for its astringent and anti-inflammatory properties.",
    botanicalName: "Argentina anserina",
    commonNames: ["Silverweed"],
    habitat: "Found in wet meadows and coastal areas.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Silverweed is used to treat digestive disorders, such as diarrhea, and is also applied externally to promote wound healing.",
    methodsOfCultivation: "Grown from seeds or divisions, Silverweed prefers moist, well-drained soil and partial shade.",
    leaf: {
      description: "The leaves are compound, with serrated leaflets and a silvery underside.",
      benefits: "Used in traditional remedies for their astringent properties.",
    },
    stem: {
      description: "The stems are creeping and root at nodes, helping the plant spread.",
      benefits: "While not directly used medicinally, the stems help the plant establish in various habitats.",
    },
    flower: {
      description: "The flowers are bright yellow with five petals.",
      benefits: "While not commonly used medicinally, they aid in the plant's reproduction.",
    },
    link: "https://youtu.be/EA_5wWagmdU",
  },
  genista: {
    title: "Genista",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Genista is a genus of flowering plants, commonly known as gorse or broom, known for its bright yellow flowers. The plant has been used traditionally for its medicinal properties, particularly for urinary health.",
    botanicalName: "Genista spp.",
    commonNames: ["Broom"],
    habitat: "Dry, sandy soils, often found in open woodland areas.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Traditionally, Genista has been used for its diuretic properties, aiding in urinary tract health.",
    methodsOfCultivation: "It is propagated from seeds or cuttings and prefers well-drained soil with full sun exposure.",
    leaf: {
      description: "Small, simple leaves, often reduced to scales in some species.",
      benefits: "The leaves contribute to the plant's photosynthesis but are not commonly used medicinally.",
    },
    stem: {
      description: "The stems are green and photosynthetic, often angular or ridged.",
      benefits: "Contain alkaloids that contribute to the plant's medicinal properties.",
    },
    flower: {
      description: "The flowers are bright yellow and pea-like.",
      benefits: "Used in traditional remedies, containing flavonoids that offer potential health benefits.",
    },
    link: "https://youtu.be/FspGsTZDDbE",
  },
  gagea: {
    title: "Gagea",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Gagea is a genus of flowering plants from the lily family, known for their delicate, star-shaped yellow flowers. They are often found in grasslands and forest edges.",
    botanicalName: "Gagea spp.",
    commonNames: ["Gagea"],
    habitat: "Found in grasslands and wooded areas across Europe and Asia.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Gagea is traditionally used to alleviate respiratory issues and support general wellness.",
    methodsOfCultivation: "Gagea is grown from bulbs or seeds, preferring well-drained soil and partial shade.",
    leaf: {
      description: "Narrow, grass-like leaves that emerge from the base of the plant.",
      benefits: "While not commonly used medicinally, they are essential for the plant’s energy production.",
    },
    stem: {
      description: "Short, slender stems that support the flowers.",
      benefits: "Primarily structural, aiding the plant's reproductive success.",
    },
    flower: {
      description: "Small, star-shaped yellow flowers.",
      benefits: "The flowers are ornamental, adding aesthetic value to gardens.",
    },
    link: "https://youtu.be/ZKBWQvS2k_c",
  },
  // Add the remaining plants following this format...

  nettle: {
    title: "Nettle",
    modelUrl: "/assets/models/nettle.glb",
    description: "Nettle (Urtica dioica), also known as Stinging Nettle, is a perennial herb with a long history of use in herbal medicine. It is rich in vitamins and minerals and is known for its stinging hairs that cause skin irritation upon contact.",
    botanicalName: "Urtica dioica",
    commonNames: ["Stinging Nettle"],
    habitat: "Commonly found in wooded areas, hedgerows, and disturbed soils.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda", "Naturopathy", "Siddha"],
    medicinalUses: "Nettle is commonly used to support joint health, alleviate allergies, and improve skin conditions. It also helps in treating urinary disorders and boosting overall immunity.",
    methodsOfCultivation: "Nettle is grown from seeds or divisions, preferring rich, moist soil and partial shade. It requires regular watering, especially during dry spells.",
    leaf: {
      description: "The leaves are dark green, heart-shaped with serrated edges, and covered in fine stinging hairs.",
      benefits: "Nettle leaves are rich in nutrients and are often used in teas, soups, and as a spinach substitute when cooked.",
    },
    stem: {
      description: "The stem is erect and square, covered in stinging hairs.",
      benefits: "The fibers from the stem are traditionally used to make textiles.",
    },
    flower: {
      description: "Small, greenish or brownish flowers that appear in drooping clusters.",
      benefits: "While not commonly used, the flowers contribute to the plant's nutritional profile and medicinal properties.",
    },
    link: "https://youtu.be/mRFZk-bPrHQ",
  },
  blackberry: {
    title: "Blackberry",
    modelUrl: "/assets/models/blackberry.glb",
    description: "Blackberry (Rubus fruticosus) is a thorny shrub known for its delicious, dark berries. It is popular in culinary dishes and offers several health benefits due to its high antioxidant content.",
    botanicalName: "Rubus fruticosus",
    commonNames: ["Blackberry"],
    habitat: "Thrives in woodlands, hedgerows, and gardens with well-drained soil.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Blackberries are rich in vitamins, antioxidants, and dietary fiber. They support heart health, boost the immune system, and aid digestion.",
    methodsOfCultivation: "Blackberries are grown from seeds or cuttings and prefer well-drained soil with full sun. They require regular pruning to promote healthy growth and fruit production.",
    leaf: {
      description: "The leaves are compound with 3-5 oval leaflets, serrated at the edges.",
      benefits: "Blackberry leaves are used in teas for their astringent properties, often helping with digestive issues and sore throats.",
    },
    stem: {
      description: "The stems, or canes, are thorny and can grow several feet long.",
      benefits: "While not used medicinally, the stems are crucial for the plant's growth and fruit production.",
    },
    flower: {
      description: "The flowers are white or pink with five petals, blooming before the berries form.",
      benefits: "While not typically used medicinally, the flowers are essential for fruit production and attract pollinators.",
    },
    link: "https://youtu.be/cLAHnZY3_OE",
  },
  daisies: {
    title: "Daisies",
    modelUrl: "/assets/models/daisies.glb",
    description: "Daisies (Bellis perennis) are well-known for their cheerful white flowers with yellow centers. They have been used in traditional medicine for their anti-inflammatory and skin-soothing properties.",
    botanicalName: "Bellis perennis",
    commonNames: ["Common Daisy"],
    habitat: "Commonly found in meadows, grassy areas, and gardens.",
    theme: "Medicinal",
    mostlyUsedIn: ["Homeopathy"],
    medicinalUses: "Daisies are used in homeopathy and herbal medicine to treat wounds, skin irritations, and inflammation. They are also believed to have mild analgesic effects.",
    methodsOfCultivation: "Daisies are grown from seeds and thrive in well-drained soil and full sun. They require moderate watering, especially during dry periods.",
    leaf: {
      description: "The leaves are spoon-shaped and form a basal rosette.",
      benefits: "Daisy leaves are sometimes used in traditional remedies for their mild astringent properties.",
    },
    stem: {
      description: "The stems are short and leafless, supporting individual flower heads.",
      benefits: "While not used medicinally, the stems support the flowers, which are the main medicinal part.",
    },
    flower: {
      description: "The flowers have white petals surrounding a yellow center disc.",
      benefits: "Daisies are used in herbal teas and topical preparations for their anti-inflammatory and skin-soothing properties.",
    },
    link: "https://youtu.be/LZg2RhBAduM",
  },
  dock: {
    title: "Dock",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Dock (Rumex spp.) is a perennial plant known for its large, broad leaves and use in traditional medicine. It is commonly found in damp, disturbed areas and is known for its astringent properties.",
    botanicalName: "Rumex spp.",
    commonNames: ["Dock Leaf"],
    habitat: "Found in wet meadows and disturbed areas with moist soil.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda"],
    medicinalUses: "Dock is used to treat digestive issues, such as constipation and diarrhea, and is also applied topically for skin irritations, particularly nettle stings.",
    methodsOfCultivation: "Dock is grown from seeds or divisions in moist, rich soil and partial shade. It requires regular watering, especially during dry spells.",
    leaf: {
      description: "The leaves are large and elongated, with wavy or curled edges.",
      benefits: "Dock leaves are often used topically to soothe skin irritations, especially those caused by nettle stings.",
    },
    stem: {
      description: "The stems are tall, ridged, and can grow several feet high.",
      benefits: "While not typically used medicinally, the stems support the plant's growth and seed production.",
    },
    flower: {
      description: "The flowers are small and greenish, arranged in whorls on tall spikes.",
      benefits: "The flowers contribute to the plant's reproduction but are not commonly used medicinally.",
    },
    link: "https://youtu.be/HU-1m5crU6A",
  },
  brookmint: {
    title: "Brookmint",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Brookmint (Mentha aquatica), also known as Water Mint, is a perennial herb commonly found near water bodies. It is known for its aromatic leaves and is often used in both culinary and medicinal applications.",
    botanicalName: "Mentha aquatica",
    commonNames: ["Water Mint"],
    habitat: "Found in wetlands, along streams, and other moist environments.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Brookmint is used to treat digestive issues and has soothing properties for stomach ailments. It is also used in teas and aromatherapy.",
    methodsOfCultivation: "Brookmint is grown from cuttings or seeds and prefers moist conditions with partial shade. It requires regular watering.",
    leaf: {
      description: "The leaves are oval to lance-shaped with serrated edges, aromatic when crushed.",
      benefits: "Used in teas and aromatherapy for their digestive and soothing properties.",
    },
    stem: {
      description: "The stems are square and often reddish in color.",
      benefits: "While not typically used medicinally, the stems support the leaves, which contain the plant's essential oils.",
    },
    flower: {
      description: "The flowers are small, lilac to pink, and appear in dense, rounded clusters.",
      benefits: "The flowers attract pollinators but are not commonly used medicinally.",
    },
    link: "https://youtu.be/6_3aM1QkWCY",
  },
  valerian: {
    title: "Valerian",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Valerian (Valeriana officinalis) is a perennial flowering plant known for its calming effects. It is widely used as a natural remedy for anxiety, insomnia, and restlessness.",
    botanicalName: "Valeriana officinalis",
    commonNames: ["Valerian Root"],
    habitat: "Grows in moist meadows and woodlands, preferring rich soil.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Valerian is used to promote relaxation, alleviate insomnia, and reduce anxiety. It is commonly consumed as a tea or in supplement form.",
    methodsOfCultivation: "Valerian can be grown from seeds or root divisions in rich, moist soil. It thrives in partial shade and requires regular watering.",
    leaf: {
      description: "The leaves are compound with serrated leaflets.",
      benefits: "While not commonly used medicinally, the leaves contribute to the plant's overall growth.",
    },
    stem: {
      description: "The stem is tall and upright, supporting the flower clusters.",
      benefits: "Primarily structural, aiding the plant's growth and flower production.",
    },
    flower: {
      description: "Valerian flowers are small, sweet-scented, and pink or white, growing in clusters.",
      benefits: "Though not the main medicinal part, the flowers contribute to the plant’s aroma and are used in teas.",
    },
    link: "https://youtu.be/jhEAYgtgPpM",
  },
  groundsel: {
    title: "Groundsel",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Groundsel (Senecio vulgaris) is a flowering plant known for its fast growth and adaptability. It is commonly found in disturbed areas and is used in traditional medicine.",
    botanicalName: "Senecio vulgaris",
    commonNames: ["Groundsel"],
    habitat: "Thrives in disturbed areas, such as waste grounds and fields.",
    theme: "Medicinal",
    mostlyUsedIn: ["Homeopathy"],
    medicinalUses: "Groundsel has been used in traditional medicine to treat various ailments, including digestive issues and respiratory conditions. However, caution is advised due to potential toxicity.",
    methodsOfCultivation: "Groundsel is grown from seeds and thrives in well-drained soil. It is drought-tolerant and requires minimal care once established.",
    leaf: {
      description: "The leaves are deeply lobed with a toothed margin.",
      benefits: "Used in some traditional remedies, though caution is advised due to its potential toxicity.",
    },
    stem: {
      description: "The stems are erect and often branching, growing up to 40cm tall.",
      benefits: "While not used medicinally, the stems support the plant's rapid growth and spread.",
    },
    flower: {
      description: "The flowers are small, yellow, and daisy-like.",
      benefits: "Not typically used medicinally, but important for the plant's reproduction and identification.",
    },
    link: "https://youtu.be/AwGi0gry-Fw",
  },
  raspberry: {
    title: "Raspberry",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Raspberry (Rubus idaeus) is a thorny shrub known for its sweet, red fruit. It is widely cultivated for culinary purposes and offers numerous health benefits, including immune and heart health support.",
    botanicalName: "Rubus idaeus",
    commonNames: ["Raspberry"],
    habitat: "Grows in woodlands and gardens, preferring well-drained soil.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Raspberries are rich in antioxidants and vitamins, supporting immune function, heart health, and digestive health.",
    methodsOfCultivation: "Raspberries are grown from seeds or cuttings and prefer well-drained soil with full sun. Regular pruning and watering are essential.",
    leaf: {
      description: "The leaves are compound with 3-5 oval leaflets, green on top and silvery underneath.",
      benefits: "Raspberry leaves are commonly used to make tea, particularly for women's health issues like menstrual discomfort.",
    },
    stem: {
      description: "The stems, or canes, are woody and covered in small prickles.",
      benefits: "While not used medicinally, they support the plant’s growth and fruit production.",
    },
    flower: {
      description: "The flowers are small, white to pink, with five petals.",
      benefits: "While not directly used, the flowers are essential for raspberry production.",
    },
    link: "https://youtu.be/NPuP6ve1O7U",
  },
  coltsfoot: {
    title: "Coltsfoot",
    modelUrl: "/assets/models/chamomile.glb",
    description: "Coltsfoot (Tussilago farfara) is a perennial herb that produces bright yellow flowers in early spring. It has been used for centuries to treat respiratory ailments, especially coughs.",
    botanicalName: "Tussilago farfara",
    commonNames: ["Coltsfoot"],
    habitat: "Commonly found in wet meadows and along roadsides.",
    theme: "Medicinal",
    mostlyUsedIn: ["Homeopathy"],
    medicinalUses: "Coltsfoot is traditionally used to relieve coughs and treat respiratory issues due to its soothing properties.",
    methodsOfCultivation: "Coltsfoot is grown from seeds and prefers moist, rich soil. It thrives in partial to full sunlight and requires regular watering.",
    leaf: {
      description: "The leaves are large, hoof-shaped, and appear after the flowers.",
      benefits: "Used in herbal preparations for respiratory conditions, particularly in cough syrups and teas.",
    },
    stem: {
      description: "The stems are scaly and bear single flower heads.",
      benefits: "While not used medicinally, they support the flowers, which are the main medicinal part.",
    },
    flower: {
      description: "The flowers are bright yellow and resemble dandelions.",
      benefits: "Used in teas and herbal preparations to soothe coughs and respiratory problems.",
    },
    link: "https://youtu.be/N73S-I8pTWA",
  },
  maizecorn: {
    title: "Maizecorn",
    modelUrl: "/assets/models/maizecorn.glb",
    description: "Maizecorn (Zea mays), commonly known as Corn or Maize, is a staple cereal crop valued for its versatility in food products. It also has several nutritional and medicinal benefits.",
    botanicalName: "Zea mays",
    commonNames: ["Corn", "Maize"],
    habitat: "Widely cultivated in warm climates, in various soil types.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Corn is rich in vitamins, antioxidants, and dietary fiber, promoting digestive health and providing energy. Corn silk is also used in traditional medicine to treat urinary issues.",
    methodsOfCultivation: "Maizecorn is grown from seeds in well-drained soil with full sun. Regular watering and pest management are crucial for successful cultivation.",
    leaf: {
      description: "The leaves are long, narrow, and have parallel veins.",
      benefits: "The leaves are crucial for the plant's photosynthesis but are not commonly used medicinally.",
    },
    stem: {
      description: "The stem is tall, sturdy, and composed of nodes and internodes.",
      benefits: "The stem channels nutrients to the developing ears of corn and is essential for the plant's growth.",
    },
    flower: {
      description: "Corn has separate male (tassel) and female (silk) flowers on the same plant.",
      benefits: "The female flowers develop into the ears of corn, providing the nutritious kernels.",
    },
    link: "https://youtu.be/vCHedpeKoXU",
  },
  aloevera: {
    title: "Aloe Vera",
    modelUrl: "/assets/models/aloevera.glb",
    description: "Aloe Vera (Aloe barbadensis) is a succulent plant known for its gel, which is used to treat burns, promote wound healing, and soothe skin irritations. It has been used in traditional medicine for centuries.",
    botanicalName: "Aloe barbadensis",
    commonNames: ["Aloe Vera"],
    habitat: "Native to tropical and subtropical regions, it thrives in dry environments.",
    theme: "Skincare",
    mostlyUsedIn: ["Ayurveda", "Naturopathy"],
    medicinalUses: "Aloe Vera gel is applied to soothe burns, wounds, and skin irritations. It is also used in skincare products for its moisturizing and anti-inflammatory properties. Internally, it can aid digestion.",
    methodsOfCultivation: "Aloe Vera is grown from offsets or seeds in well-drained soil with full sun. It requires minimal watering and is drought-resistant.",
    leaf: {
      description: "The leaves are thick, fleshy, and spiny at the edges, containing a clear gel.",
      benefits: "Aloe Vera gel is widely used for its soothing, healing, and moisturizing properties.",
    },
    stem: {
      description: "The stem is short and often not visible, as the leaves grow in a rosette pattern.",
      benefits: "While not used medicinally, the stem supports the growth of the medicinal leaves.",
    },
    flower: {
      description: "The flowers are tubular, yellow or orange, and grow on a tall spike.",
      benefits: "While not commonly used medicinally, the flowers contribute to the plant's health and reproduction.",
    },
    link: "https://youtu.be/F06wSDOyIqM",
  },
  jadeplant: {
    title: "Jade Plant",
    modelUrl: "/assets/models/jadeplant.glb",
    description: "The Jade Plant (Crassula ovata) is a succulent known for its thick, fleshy leaves and ease of care. Often associated with good luck and prosperity, it is commonly grown as a houseplant.",
    botanicalName: "Crassula ovata",
    commonNames: ["Jade Plant", "Money Tree"],
    habitat: "Native to South Africa, often grown indoors in pots.",
    theme: "Skincare",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "While primarily grown as an ornamental plant, Jade leaves have been used in traditional remedies for minor skin irritations and warts.",
    methodsOfCultivation: "Jade plants are grown from leaves or stem cuttings, thriving in well-drained soil with bright sunlight. They require minimal watering and are drought-tolerant.",
    leaf: {
      description: "The leaves are thick, oval-shaped, and fleshy with a smooth, waxy texture.",
      benefits: "In traditional medicine, the leaves are sometimes used topically for minor skin irritations.",
    },
    stem: {
      description: "The stem is thick and woody, becoming tree-like with age.",
      benefits: "While not used medicinally, the stem supports the growth of the leaves and contributes to the plant's overall structure.",
    },
    flower: {
      description: "The flowers are small, star-shaped, and pink or white, appearing in clusters.",
      benefits: "Not typically used medicinally, but they add ornamental value to the plant.",
    },
    link: "https://youtu.be/_bfDHL252LM",
  },
  malefern: {
    title: "Male Fern",
    modelUrl: "/assets/models/malefern.glb",
    description: "Male Fern (Dryopteris filix-mas) is a hardy fern known for its feathery fronds. It has a long history of medicinal use, particularly in treating intestinal parasites and skin conditions.",
    botanicalName: "Dryopteris filix-mas",
    commonNames: ["Male Fern"],
    habitat: "Commonly found in wooded areas and shaded locations.",
    theme: "Medicinal",
    mostlyUsedIn: ["Naturopathy"],
    medicinalUses: "Male Fern has been traditionally used as an anthelmintic, especially for expelling intestinal worms. It has also been applied to treat various skin conditions.",
    methodsOfCultivation: "Male Fern can be propagated by spores or divisions, preferring rich, moist soil in partial to full shade.",
    leaf: {
      description: "The leaves are large, feathery fronds with pinnate leaflets.",
      benefits: "Fronds contain compounds traditionally used for their anthelmintic properties.",
    },
    stem: {
      description: "The stem is a short, thick rhizome covered in brown scales.",
      benefits: "The rhizome is the main part used medicinally, containing most of the active compounds.",
    },
    flower: {
      description: "As a fern, it does not produce flowers but reproduces via spores.",
      benefits: "The spores, located on the underside of the fronds, are not typically used medicinally.",
    },
    link: "https://youtu.be/1Qf3w02CYhc",
  },
  neem: {
    title: "Neem",
    modelUrl: "/assets/models/neem.glb",
    description: "Neem (Azadirachta indica) is a fast-growing tree known for its medicinal properties. Every part of the tree, from the bark to the leaves, has been used in traditional medicine, especially in Ayurveda and Unani.",
    botanicalName: "Azadirachta indica",
    commonNames: ["Neem", "Indian Lilac"],
    habitat: "Grows in tropical and subtropical regions, particularly in India.",
    theme: "Medicinal",
    mostlyUsedIn: ["Ayurveda", "Unani", "Siddha"],
    medicinalUses: "Neem is valued for its antibacterial, antifungal, and antiviral properties. It is commonly used in skin treatments, dental care, and to boost overall immunity.",
    methodsOfCultivation: "Neem is grown from seeds or cuttings in well-drained soil. It thrives in full sun and is drought-resistant once established.",
    leaf: {
      description: "The leaves are compound, with serrated leaflets.",
      benefits: "Neem leaves are used in various medicinal preparations for their antimicrobial and anti-inflammatory properties.",
    },
    stem: {
      description: "The bark is rough and dark brown.",
      benefits: "Neem bark is used in traditional medicine for its astringent and antimicrobial properties.",
    },
    flower: {
      description: "The flowers are small, white, and fragrant, arranged in drooping panicles.",
      benefits: "While not commonly used medicinally, neem flowers are sometimes used in culinary preparations.",
    },
    link: "https://youtu.be/ZCq0ZVRWCPQ",
  }
};


